### ISSUE TITLE
Feature Request: What is also needed

### ISSUE THREAD

**Issue by vtimofeev01** [dlstreamer/pipeline-server#26]
Thank U for wonderful made product!

really are extra needed some extra:

there is no possibility to enumerate all pipes having status via RESTapi
for example it will be great to get with GET /pipelines/{name}/{version} list of ids to get status or make an separate query to read list of ids 

it will be great to have a /reload and /exit command 

also will be grate to add to status data CPU usage (via psutil)

Thank U

**Comment by nnshah1** [comment]
@vtimofeev01 Thanks for the feedback! Appreciate it - we will look into providing these.

GET /pipelines/name/version, would be fairly straight forward.

/reload, /exit. If I understand this correctly - this is an API to reload the pipeline definitions and model discovery? Is that a feature you'd using during deployment or just for debugging? My first inclination is to offer this as an option during startup (i.e. whether to include the 'admin' api) - to support deployments that are 'hardened' and unchangeable and those that need to be dynamic. I understand the usecase for /reload, but not as sure about /exit. Can you describe how you might use /exit?

On CPU usage - we are also considering integration into telegraf / prometheus / collectd - is there a particular telemetry framework that would be more valuable than others? And would you prefer this to come via the status call or as integrated into a telemetry api?

Thanks again for the feedback!

Neelay

@whbruce

**Comment by vtimofeev01** [comment]
Thank U
in my situation reload was needed during debugging, otherwise i needed to stop and reload docker image
also Ctrl-C was frequantly not working to stop VA in container, but REST API works and it could be a way to stop VAServing

About CPU usage - at your choice

The enumerating of running pipes will be also good

Thanks again

**Comment by whbruce** [comment]
Here is status on your feature requests:
1. CTRL+C not stopping REST service: this was fixed in v0.4.0
2. `reload` and `exit` commands: no near term plans to add to REST API
2. CPU usage: no near term plans to add to status request.
3. Enumerating running pipelines: will be added in our June release at end of Q2.

**Comment by whbruce** [comment]
Here is updated status on your feature requests:
1. CTRL+C not stopping REST service: this was fixed in v0.4.0
1. `reload` command: will be added to a future release 
1. `exit` command: will not be supported
1. CPU usage: will not be added to status message but may be used in future versions of Kubernetes deployment
1. Enumerating running pipelines: this was fixed in v0.7.1

**Comment by akwrobel** [comment]
This feature has been reviewed and is not a roadmap target for the current product.
