### ISSUE TITLE
Prevent pipeline instances from resetting 

### ISSUE THREAD

**Issue by amajai** [dlstreamer/pipeline-server#58]
I noticed that every time you restart the api server, the pipeline instances from the last session will all be lost and get reset to zero. Is there a way to create some sort of a storage for saving pipeline instances so you can have access to it anytime without having to lose them every time you restart the server?

**Comment by whbruce** [comment]
This is expected behavior as pipelines will be stopped with service and will not retain state across re-start. Although pipeline instances are currently incrementing values, clients should not make this assumption as behavior may change in future versions of the service.

If a client loses connection with service, there is no easy way to reconnect and get running pipeline instances. This feature will be added in a future release. In the meantime you could write code to speculatively query for pipeline instances to simulate an enumeration call, but it may need some knowledge of the pattern used to start the instances.

**Comment by amajai** [comment]
@whbruce Thanks for the response. I will try to code the feature to keep count of the instances. I look forward to the future release.

**Comment by whbruce** [comment]
Issue #92 prevents you from speculatively querying for pipeline instances.

**Comment by whbruce** [comment]
Fixed in v0.7.1
